---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: http-https-echo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: http-https-echo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: http-https-echo
    spec:
      containers:
        - name: http-https-echo
          image: mendhak/http-https-echo
          imagePullPolicy: Always
          env:
            - name: ECHO_INCLUDE_ENV_VARS
              value: "1"
            - name: __TIME
              value: "1:02pm"
          ports:
            - name: http
              containerPort: 8080
