---
name: CI - OCI CLI Example

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

# See: https://github.com/marketplace/actions/run-an-oracle-cloud-infrastructure-oci-cli-command
env:
  OCI_CLI_USER: "${{ secrets.OCI_CLI_USER }}"
  OCI_CLI_TENANCY: "${{ secrets.OCI_CLI_TENANCY }}"
  OCI_CLI_FINGERPRINT: "${{ secrets.OCI_CLI_FINGERPRINT }}"
  OCI_CLI_KEY_CONTENT: "${{ secrets.OCI_CLI_KEY_CONTENT }}"
  OCI_CLI_REGION: "${{ secrets.OCI_CLI_REGION }}"

jobs:
  kubectl:
    name: Apply
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4

      - name: Show oci version.
        uses: oracle-actions/run-oci-cli-command@v1.1.1
        with:
          # oci --version
          command: '--version'
          silent: false

      - name: Show oci help.
        uses: oracle-actions/run-oci-cli-command@v1.1.1
        with:
          # oci --help
          command: '--help'
          silent: false

      - name: List IAM users.
        uses: oracle-actions/run-oci-cli-command@v1.1.1
        with:
          # oci iam user list
          command: 'iam user list'
